import { ACTION_VERSIONS } from "./actionVersions.ts";

export const CODEX_WORKFLOW_PATH = ".github/workflows/codex-review.yml";

/** Pinned so the cache key is deterministic and an upgrade is a visible diff. */
const CODEX_VERSION = "0.125.0";

const PROMPT = [
  "Review the diff between the base branch and HEAD of this pull request.",
  "Report only defects you can point at: a wrong result, an unhandled failure, a race, a",
  "security hole. Skip style — a formatter and a linter already ran.",
  "End with exactly one line: `CODEX VERDICT: LGTM` or `CODEX VERDICT: CHANGES REQUESTED`.",
].join(" ");

const HEADER = [
  "# Generated by ever-better. A second model reviews every pull request.",
  "#",
  "# Needs an OPENAI_API_KEY repository secret. Without it the job reports that and passes —",
  "# a check that is red until somebody adds a secret is a check everyone learns to ignore.",
  "name: codex-review",
  "",
  "on:",
  "  pull_request:",
  "    types: [opened, synchronize, reopened]",
  "  workflow_dispatch:",
  "",
  "permissions:",
  "  contents: read",
  "",
  "concurrency:",
  "  group: codex-review-${{ github.event.pull_request.number || github.ref }}",
  "  cancel-in-progress: true",
  "",
  "env:",
  `  CODEX_VERSION: "${CODEX_VERSION}"`,
  "",
  "jobs:",
  "  codex-review:",
  "    # Dependabot pull requests receive no repository secrets, so the key would resolve to an",
  "    # empty string and the review would fail seconds in. A version bump gains nothing from it.",
  "    if: github.actor != 'dependabot[bot]'",
  "    runs-on: ubuntu-latest",
  "    timeout-minutes: 15",
  "    permissions:",
  "      contents: read",
  "      pull-requests: write # to post the review as a comment",
  "    steps:",
];

const KEY_CHECK = [
  "      - name: Check for the API key",
  "        id: key",
  "        env:",
  "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}",
  "        run: |",
  '          if [ -n "$OPENAI_API_KEY" ]; then',
  '            echo "present=true" >> "$GITHUB_OUTPUT"',
  "          else",
  '            echo "present=false" >> "$GITHUB_OUTPUT"',
  '            echo "::notice::OPENAI_API_KEY is not set — skipping the Codex review."',
  "          fi",
  "",
];

/** Every step past the key check is gated on it, which is what makes the absent-key run green. */
const GATE = "        if: steps.key.outputs.present == 'true'";

const setupSteps = (nodeVersion: string): string[] => [
  `      - uses: ${ACTION_VERSIONS.checkout}`,
  GATE,
  "        with:",
  "          # Codex needs the full history to diff the pull request.",
  "          fetch-depth: 0",
  "          persist-credentials: false",
  "",
  `      - uses: ${ACTION_VERSIONS.setupNode}`,
  GATE,
  "        with:",
  `          node-version: "${nodeVersion}"`,
  "",
  "      - name: Install the Codex CLI",
  GATE,
  '        run: npm install -g "@openai/codex@${CODEX_VERSION}"',
  "",
];

const REVIEW_STEP = [
  "      - name: Review",
  GATE,
  "        env:",
  "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}",
  "          GH_TOKEN: ${{ github.token }}",
  "          BASE: ${{ github.event.pull_request.base.sha }}",
  "        run: |",
  "          set -euo pipefail",
  '          git diff "$BASE"...HEAD > /tmp/pr.diff',
  "          codex exec --skip-git-repo-check \\",
  `            "${PROMPT}" \\`,
  "            < /tmp/pr.diff > /tmp/review.md",
  '          cat /tmp/review.md >> "$GITHUB_STEP_SUMMARY"',
  '          gh pr comment "${{ github.event.pull_request.number }}" --body-file /tmp/review.md',
  "",
];

/**
 * A second model reading the diff. The point is not that it is better than the first — it is that
 * it is different, and two reviewers with the same blind spot find the same nothing.
 */
export const renderCodexReviewWorkflow = (nodeVersion: string): string =>
  [...HEADER, ...KEY_CHECK, ...setupSteps(nodeVersion), ...REVIEW_STEP].join("\n");
