import type { PackageManager } from "../types.ts";

const ECOSYSTEM: Record<PackageManager, string> = {
  yarn: "npm",
  npm: "npm",
  pnpm: "npm",
  bun: "npm",
};

/**
 * The generated workflows pin action majors, and a pinned version rots silently — a workflow two
 * majors behind still runs, so nothing ever reports it. Dependabot is what keeps them current
 * after this tool has stopped looking, which is why bootstrap writes this rather than trusting its
 * own constants to stay fresh.
 *
 * The lint stack is grouped because `typescript-eslint`'s peer range pins which ESLint it accepts:
 * bumped separately, neither PR can merge on its own.
 */
export const renderDependabot = (packageManager: PackageManager): string =>
  [
    "# Generated by ever-better. Keeps the pinned action versions and the lint stack current.",
    "version: 2",
    "",
    "updates:",
    `  - package-ecosystem: ${ECOSYSTEM[packageManager]}`,
    "    directory: /",
    "    schedule:",
    "      interval: weekly",
    "    open-pull-requests-limit: 5",
    "    groups:",
    "      eslint:",
    "        patterns:",
    '          - "eslint"',
    '          - "eslint-*"',
    '          - "@eslint/*"',
    '          - "typescript-eslint"',
    '          - "globals"',
    "",
    "  - package-ecosystem: github-actions",
    "    directory: /",
    "    schedule:",
    "      interval: weekly",
    "    open-pull-requests-limit: 3",
    "",
  ].join("\n");
