import { frameworkIgnores } from "../detect/framework.ts";
import { frameworkParts } from "./frameworkBlocks.ts";
import type { Framework, PackageJson, Runtime, TestRunner } from "../types.ts";

export type EslintConfigOptions = {
  /** Type-aware rules find the most real bugs and cost the most time. Off for JS-only repos. */
  typed: boolean;
  fileLineLimit: number;
  testGlob: string;
  testRunner: TestRunner;
  framework: Framework;
  runtime: Runtime;
};

const BASE_PACKAGES = [
  "eslint",
  "@eslint/js",
  "globals",
  "typescript-eslint",
  "eslint-plugin-sonarjs",
  "eslint-config-prettier",
  // Prettier runs AS a lint rule rather than as a separate command. That is what puts formatting
  // inside the ratchet: a violation is an error like any other, `eslint --fix` repairs it, and CI
  // needs one gate instead of two that can disagree.
  "eslint-plugin-prettier",
];

/*
 * Import-cycle detection is deliberately absent, and it took three attempts to establish why:
 *
 *   - `eslint-plugin-import` peers at eslint ^9, so it cannot be installed beside ESLint 10.
 *   - `eslint-plugin-import-x` does support 10, but `no-cycle` needs a resolver that understands
 *     TypeScript. `flatConfigs.typescript` names `eslint-import-resolver-typescript`, whose
 *     optional peer drags `eslint-plugin-import` back in and fails the whole install.
 *   - import-x's own `createNodeResolver`, told about `.ts`, loads without error and then reports
 *     nothing at all on a genuine two-file cycle. Measured, not assumed.
 *
 * An enabled rule that silently finds nothing is the worst of the three: it reads as proof the
 * codebase has no cycles. Revisit when the import ecosystem has caught up with ESLint 10.
 */

/**
 * The security plugin only where its rules can apply: everything it looks for — child processes,
 * non-literal fs paths, unsafe regexes — is Node-side. On a browser-only bundle it is noise.
 */
const securityPackages = (runtime: Runtime): string[] => (runtime === "browser" ? [] : ["eslint-plugin-security"]);

export const eslintPackagesFor = (framework: Framework, runtime: Runtime = "node"): string[] => [
  ...BASE_PACKAGES,
  ...securityPackages(runtime),
  ...frameworkParts(framework, true).packages,
];

/**
 * The config is written as ESM either way. In a package without `"type": "module"` — which is most
 * React and Next projects — a `.js` file is CommonJS, so Node reparses it and warns on every lint
 * run. `.mjs` states the format instead of relying on a field the repo may never set.
 */
export const eslintConfigFileName = (packageJson: PackageJson | null): string => (packageJson?.type === "module" ? "eslint.config.js" : "eslint.config.mjs");

const HEADER = [
  "// Generated by ever-better. This file is yours — edit it.",
  "//",
  "// Every rule below is an ERROR, and every violation that existed when you ran",
  "// `ever-better freeze` is recorded in eslint-suppressions.json. Old code is grandfathered;",
  "// new code is held to the whole standard from the first commit. Do not soften a rule to make",
  "// a red build green — the suppressions file already did that, once, on purpose.",
  "//",
  "// Type assertions are banned outright: `as`, `<T>x`, `!`, `@ts-ignore`, `@ts-nocheck`. Each is a",
  "// claim the compiler could not check and that no reviewer can see. Write a type guard instead —",
  "// `const isThing = (v: unknown): v is Thing => ...` — which is testable, narrows for every",
  "// caller, and fails at the boundary where the data was actually wrong.",
  "",
];

const BASE_IMPORTS = [
  'import js from "@eslint/js";',
  'import globals from "globals";',
  'import tseslint from "typescript-eslint";',
  'import sonarjs from "eslint-plugin-sonarjs";',
  'import prettierRecommended from "eslint-plugin-prettier/recommended";',
];

const GLOBALS_EXPRESSION: Record<Runtime, string> = {
  browser: "globals.browser",
  node: "globals.node",
  // A frontend repo still runs its config files, scripts and tests under Node, so browser-only
  // globals produce a wall of `no-undef` that says nothing about the code.
  both: "{ ...globals.browser, ...globals.node }",
};

const ignoresLine = (framework: Framework): string => {
  const patterns = frameworkIgnores(framework)
    .map((pattern) => `"${pattern}"`)
    .join(", ");
  return `  { ignores: [${patterns}] },`;
};

const typedBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) {
    return [
      "  // Type-aware rules are off: this repo is not TypeScript yet. They are where the real",
      "  // bugs are found, so migrating unlocks the most valuable tier — see `ever-better diagnose`.",
      "  tseslint.configs.recommended,",
    ];
  }
  return [
    "  // strictTypeChecked, not recommended: the type-aware rules that find real bugs are only in",
    "  // the TypeChecked presets, and the strict variant is where the `any` family lives.",
    "  tseslint.configs.strictTypeChecked,",
    "  // The two are disjoint; typescript-eslint's own advice is to use both.",
    "  tseslint.configs.stylisticTypeChecked,",
    "  {",
    "    languageOptions: {",
    "      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },",
    "    },",
    "  },",
  ];
};

/**
 * Rules that keep the code readable to whoever arrives next, rather than correct. `id-length`
 * carries exceptions because a loop counter and a discarded binding are not the problem it is
 * aimed at — a variable called `d` holding a customer record is.
 */
const readabilityBlock = (): string[] => [
  "  {",
  "    rules: {",
  "      // A loop counter and a discarded binding are not what this is aimed at; a variable called",
  "      // `d` holding a customer record is. `js`, `fs`, `os` are the conventional module aliases.",
  '      "id-length": [',
  '        "error",',
  '        { min: 3, exceptions: ["_", "i", "j", "k", "id", "ok", "to", "up", "js", "fs", "os"] },',
  "      ],",
  "    },",
  "  },",
];

const limitsBlock = (options: EslintConfigOptions): string[] => [
  "  {",
  "    // Size and complexity guards. These are the ones that turn into refactoring work rather",
  "    // than one-line fixes, which is exactly why they are recorded rather than negotiated.",
  "    rules: {",
  `      "max-lines": ["error", { max: ${options.fileLineLimit}, skipBlankLines: true, skipComments: true }],`,
  '      "max-lines-per-function": ["error", { max: 50, skipBlankLines: true, skipComments: true }],',
  '      complexity: ["error", 15],',
  '      "max-depth": ["error", 4],',
  '      "max-nested-callbacks": ["error", 4],',
  '      "max-params": ["error", 6],',
  '      "sonarjs/cognitive-complexity": ["error", 15],',
  "    },",
  "  },",
];

const strictnessBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) return [];
  return [
    "  {",
    "    // Types as a second rule set. `any` and `!` are how a type system gets talked out of",
    "    // doing its job, and both are invisible in review.",
    "    rules: {",
    '      "@typescript-eslint/no-explicit-any": "error",',
    '      "@typescript-eslint/no-non-null-assertion": "error",',
    '      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^__" }],',
    "      // `as` asserts what the compiler could not check, and it is invisible in review. Write a",
    "      // type guard instead — the guard is testable and the assertion is a promise.",
    '      "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: "never" }],',
    "      // The other doors out of the type system. `@ts-expect-error` survives only with a",
    "      // written reason, because it is the one that fails loudly when it stops being needed.",
    '      "@typescript-eslint/ban-ts-comment": [',
    '        "error",',
    "        {",
    '          "ts-ignore": true,',
    '          "ts-nocheck": true,',
    '          "ts-check": false,',
    '          "ts-expect-error": "allow-with-description",',
    "          minimumDescriptionLength: 10,",
    "        },",
    "      ],",
    "    },",
    "  },",
  ];
};

/**
 * Config files are not in the TypeScript program, so the type-aware parser refuses them outright
 * ("was not found by the project service") — a parse error that no rule can suppress and that
 * makes the very first `eslint .` after bootstrap look broken.
 */
const configFileBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) return [];
  return [
    "  {",
    '    files: ["**/*.config.js", "**/*.config.mjs", "**/*.config.cjs"],',
    "    languageOptions: { parserOptions: { projectService: false } },",
    "    ...tseslint.configs.disableTypeChecked,",
    "  },",
  ];
};

// node:test's `describe`/`it` return promises the runner owns; awaiting them is wrong, and
// `void`-prefixing every block would be noise on every line of every spec.
const nodeTestRule = (options: EslintConfigOptions): string[] =>
  options.testRunner === "node:test" && options.typed ? ['      "@typescript-eslint/no-floating-promises": "off",'] : [];

const testBlock = (options: EslintConfigOptions): string[] => [
  "  {",
  "    // A spec repeats itself by nature and its length is not a comprehension problem.",
  `    files: ["${options.testGlob}"],`,
  "    rules: {",
  '      "max-lines": "off",',
  '      "max-lines-per-function": "off",',
  '      "sonarjs/no-duplicate-string": "off",',
  ...nodeTestRule(options),
  "    },",
  "  },",
];

/**
 * A stale `eslint-disable` is an exception nobody re-examined. Reporting the ones that no longer
 * suppress anything is the only way they ever get removed — and a disable comment left behind after
 * a refactor is how a rule quietly stops applying to a file.
 */
const disableDirectiveBlock = (): string[] => ["  {", "    linterOptions: {", '      reportUnusedDisableDirectives: "error",', "    },", "  },"];

const securityImport = (runtime: Runtime): string[] => (runtime === "browser" ? [] : ['import security from "eslint-plugin-security";']);

const securityBlock = (runtime: Runtime): string[] => (runtime === "browser" ? [] : ["  security.configs.recommended,"]);

export const renderEslintConfig = (options: EslintConfigOptions): string => {
  const framework = frameworkParts(options.framework, options.typed);
  return [
    ...HEADER,
    ...BASE_IMPORTS,
    ...securityImport(options.runtime),
    ...framework.imports,
    "",
    "export default tseslint.config(",
    ignoresLine(options.framework),
    ...disableDirectiveBlock(),
    "",
    "  js.configs.recommended,",
    ...typedBlock(options),
    "  sonarjs.configs.recommended,",
    ...securityBlock(options.runtime),
    ...framework.configs,
    // Last: it switches off every rule that would argue with the formatter, so anything after it
    // could turn one back on.
    "  prettierRecommended,",
    "",
    `  { languageOptions: { globals: ${GLOBALS_EXPRESSION[options.runtime]} } },`,
    "",
    ...strictnessBlock(options),
    ...limitsBlock(options),
    ...readabilityBlock(),
    ...testBlock(options),
    ...configFileBlock(options),
    ");",
    "",
  ].join("\n");
};
