import type { TestRunner } from "../types.ts";

export type EslintConfigOptions = {
  /** Type-aware rules find the most real bugs and cost the most time. Off for JS-only repos. */
  typed: boolean;
  fileLineLimit: number;
  testGlob: string;
  testRunner: TestRunner;
};

export const ESLINT_PACKAGES = [
  "eslint",
  "@eslint/js",
  "globals",
  "typescript-eslint",
  "eslint-plugin-sonarjs",
  "eslint-config-prettier",
];

const HEADER = [
  "// Generated by ever-better. This file is yours — edit it.",
  "//",
  "// Every rule below is an ERROR, and every violation that existed when you ran",
  "// `ever-better freeze` is recorded in eslint-suppressions.json. Old code is grandfathered;",
  "// new code is held to the whole standard from the first commit. Do not soften a rule to make",
  "// a red build green — the suppressions file already did that, once, on purpose.",
  "",
];

const IMPORTS = [
  'import js from "@eslint/js";',
  'import globals from "globals";',
  'import tseslint from "typescript-eslint";',
  'import sonarjs from "eslint-plugin-sonarjs";',
  'import prettier from "eslint-config-prettier";',
  "",
];

const typedBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) {
    return [
      "  // Type-aware rules are off: this repo is not TypeScript yet. They are where the real",
      "  // bugs are found, so migrating unlocks the most valuable tier — see `ever-better diagnose`.",
      "  tseslint.configs.recommended,",
    ];
  }
  return [
    "  tseslint.configs.recommendedTypeChecked,",
    "  {",
    "    languageOptions: {",
    "      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },",
    "    },",
    "  },",
  ];
};

const limitsBlock = (options: EslintConfigOptions): string[] => [
  "  {",
  "    // Size and complexity guards. These are the ones that turn into refactoring work rather",
  "    // than one-line fixes, which is exactly why they are recorded rather than negotiated.",
  "    rules: {",
  `      "max-lines": ["error", { max: ${options.fileLineLimit}, skipBlankLines: true, skipComments: true }],`,
  '      "max-lines-per-function": ["error", { max: 60, skipBlankLines: true, skipComments: true }],',
  '      complexity: ["error", 20],',
  '      "max-depth": ["error", 4],',
  '      "max-nested-callbacks": ["error", 4],',
  '      "sonarjs/cognitive-complexity": ["error", 15],',
  "    },",
  "  },",
];

const strictnessBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) return [];
  return [
    "  {",
    "    // Types as a second rule set. `any` and `!` are how a type system gets talked out of",
    "    // doing its job, and both are invisible in review.",
    "    rules: {",
    '      "@typescript-eslint/no-explicit-any": "error",',
    '      "@typescript-eslint/no-non-null-assertion": "error",',
    '      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^__" }],',
    "    },",
    "  },",
  ];
};

/**
 * Config files are not in the TypeScript program, so the type-aware parser refuses them outright
 * ("was not found by the project service") — a parse error that no rule can suppress and that
 * makes the very first `eslint .` after bootstrap look broken.
 */
const configFileBlock = (options: EslintConfigOptions): string[] => {
  if (!options.typed) return [];
  return [
    "  {",
    '    files: ["**/*.config.js", "**/*.config.mjs", "**/*.config.cjs"],',
    "    languageOptions: { parserOptions: { projectService: false } },",
    "    ...tseslint.configs.disableTypeChecked,",
    "  },",
  ];
};

// node:test's `describe`/`it` return promises the runner owns; awaiting them is wrong, and
// `void`-prefixing every block would be noise on every line of every spec.
const nodeTestRule = (options: EslintConfigOptions): string[] =>
  options.testRunner === "node:test" && options.typed
    ? ['      "@typescript-eslint/no-floating-promises": "off",']
    : [];

const testBlock = (options: EslintConfigOptions): string[] => [
  "  {",
  "    // A spec repeats itself by nature and its length is not a comprehension problem.",
  `    files: ["${options.testGlob}"],`,
  "    rules: {",
  '      "max-lines": "off",',
  '      "max-lines-per-function": "off",',
  '      "sonarjs/no-duplicate-string": "off",',
  ...nodeTestRule(options),
  "    },",
  "  },",
];

export const renderEslintConfig = (options: EslintConfigOptions): string =>
  [
    ...HEADER,
    ...IMPORTS,
    "export default tseslint.config(",
    '  { ignores: ["dist/**", "build/**", "coverage/**", "node_modules/**"] },',
    "",
    "  js.configs.recommended,",
    ...typedBlock(options),
    "  sonarjs.configs.recommended,",
    "  prettier,",
    "",
    "  { languageOptions: { globals: globals.node } },",
    "",
    ...strictnessBlock(options),
    ...limitsBlock(options),
    ...testBlock(options),
    ...configFileBlock(options),
    ");",
    "",
  ].join("\n");
