import { ACTION_VERSIONS } from "./actionVersions.ts";
import type { PackageManager } from "../types.ts";

const INSTALL: Record<PackageManager, string> = {
  yarn: "yarn install --frozen-lockfile",
  npm: "npm ci",
  pnpm: "pnpm install --frozen-lockfile",
  bun: "bun install --frozen-lockfile",
};

const SETUP: Partial<Record<PackageManager, string[]>> = {
  pnpm: [`      - uses: ${ACTION_VERSIONS.pnpmSetup}`, ""],
  bun: [`      - uses: ${ACTION_VERSIONS.bunSetup}`, ""],
};

export const GATE_WORKFLOW_PATH = ".github/workflows/ever-better.yml";

/**
 * A separate workflow file rather than a step spliced into one the repo already wrote.
 *
 * The alternative is editing someone's YAML, and nothing here parses YAML — appending to a file
 * whose shape is unknown is how a working pipeline gets broken by a tool that was supposed to help.
 * A repo with its own CI still needs this: the baseline is only a ratchet if something rejects a
 * regression, and thorough CI that never runs `check` enforces exactly nothing.
 */
export const renderGateWorkflow = (packageManager: PackageManager, nodeVersion: string): string =>
  [
    "# Generated by ever-better. Its own workflow on purpose: adding a step to a pipeline this",
    "# tool did not write would mean editing YAML it cannot parse.",
    "name: ever-better",
    "",
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "  workflow_dispatch:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  check:",
    "    name: ever-better check",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 15",
    "    steps:",
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    "        with:",
    "          persist-credentials: false",
    "",
    ...(SETUP[packageManager] ?? []),
    `      - uses: ${ACTION_VERSIONS.setupNode}`,
    "        with:",
    `          node-version: "${nodeVersion}"`,
    "",
    `      - run: ${INSTALL[packageManager]}`,
    "",
    "      - name: ever-better check",
    "        run: npx --yes ever-better check --no-write",
    "",
  ].join("\n");
