const BINARY_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "ico", "woff", "woff2", "pdf"];

/**
 * Git checks out CRLF on Windows by default while Prettier normalises to LF, so a repository
 * without this reports every single file as unformatted — but only on the Windows runner, and only
 * once someone adds one. Since bootstrap generates a three-platform workflow, it has to write this
 * too or it hands the user a red build they did not have before.
 */
export const renderGitattributes = (): string =>
  [
    "# Generated by ever-better.",
    "#",
    "# Without `eol=lf`, Windows checks out CRLF and every formatter and linter reports the whole",
    "# repository as wrong — a failure that appears on one runner only.",
    "* text=auto eol=lf",
    "",
    ...BINARY_EXTENSIONS.map((extension) => `*.${extension} binary`),
    "",
  ].join("\n");
