import { CONFIG_SAMPLES, WORKFLOW_SAMPLES, type Sample } from "./samples.ts";
import { STRICTNESS_SAMPLE } from "./strictnessSample.ts";

const block = (sample: Sample): string[] => [`### ${sample.title}`, "", sample.note, "", "```" + sample.language, sample.contents.trimEnd(), "```", ""];

const HEADER = [
  "# What you end up with",
  "",
  "<!-- Generated by `yarn docs`. Rendered from the generators themselves, so it cannot drift;",
  "     a test fails if this file and the code disagree. Do not edit by hand. -->",
  "",
  "Everything on this page is what `ever-better bootstrap` actually writes, rendered by the same",
  "code that writes it. Yours will differ where your repository does — the framework, the package",
  "manager, and whether it is TypeScript yet.",
  "",
  "Every file is yours after it is written. The one rule is that softening a rule to clear a red",
  "build is the wrong move: the suppressions file already granted every exception that was",
  "justified.",
  "",
];

export const renderSamplesDoc = (): string =>
  [
    ...HEADER,
    "## Configuration",
    "",
    ...CONFIG_SAMPLES.flatMap(block),
    "## tsconfig.json",
    "",
    STRICTNESS_SAMPLE,
    "",
    "## Workflows",
    "",
    ...WORKFLOW_SAMPLES.flatMap(block),
  ].join("\n");
