import { ACTION_VERSIONS } from "./actionVersions.ts";
import type { PackageManager } from "../types.ts";

const INSTALL: Record<PackageManager, string> = {
  yarn: "yarn install --frozen-lockfile",
  npm: "npm ci",
  pnpm: "pnpm install --frozen-lockfile",
  bun: "bun install --frozen-lockfile",
};

const RUN: Record<PackageManager, string> = {
  yarn: "yarn",
  npm: "npm run",
  pnpm: "pnpm",
  bun: "bun run",
};

const SETUP: Partial<Record<PackageManager, string[]>> = {
  pnpm: [`      - uses: ${ACTION_VERSIONS.pnpmSetup}`, ""],
  bun: [`      - uses: ${ACTION_VERSIONS.bunSetup}`, ""],
};

const JSCPD_FORMATS = "typescript,javascript,jsx,tsx,vue";

/**
 * Duplication, into GitHub Code Scanning. Never fails the build, and that is a rule rather than a
 * stage: a global duplication percentage cannot stop new duplication — twenty copied lines added
 * to a hundred thousand move it by a hundredth of a point — so any threshold you passed before the
 * copy you still pass after it. SARIF is what makes the finding per-pull-request instead.
 */
export const renderDuplicationWorkflow = (nodeVersion: string): string =>
  [
    "# Generated by ever-better. Report-only: a check that cannot point at what THIS diff added",
    "# must not gate, or the first false failure teaches everyone to reach for an ignore comment.",
    "name: duplication-scan",
    "",
    "on:",
    "  pull_request:",
    "    paths-ignore:",
    '      - "**/*.md"',
    "  push:",
    "    branches: [main]",
    "  workflow_dispatch:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  duplication-scan:",
    "    name: Duplication Scan (jscpd)",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    permissions:",
    "      contents: read",
    "      security-events: write # required to upload SARIF",
    "    steps:",
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    "        with:",
    "          persist-credentials: false",
    "",
    `      - uses: ${ACTION_VERSIONS.setupNode}`,
    "        with:",
    `          node-version: "${nodeVersion}"`,
    "",
    "      - name: Run jscpd",
    "        run: |",
    "          set -euo pipefail",
    "          npx --yes jscpd@4 . \\",
    `            --format "${JSCPD_FORMATS}" \\`,
    '            --ignore "**/node_modules/**,**/dist/**,**/build/**,**/*.d.ts" \\',
    "            --reporters console,sarif \\",
    "            --output report",
    "",
    "      - name: Upload SARIF to Code Scanning",
    `        uses: ${ACTION_VERSIONS.uploadSarif}`,
    "        with:",
    "          sarif_file: report/jscpd-sarif.json",
    "          category: jscpd",
    "",
  ].join("\n");

/**
 * Dead code, into the job summary. Also report-only: knip has no base-branch diffing, so it lists
 * the whole inventory and cannot say what this pull request orphaned.
 */
export const renderDeadCodeWorkflow = (packageManager: PackageManager, nodeVersion: string): string =>
  [
    "# Generated by ever-better. Report-only — knip lists the whole inventory and cannot say what",
    "# THIS pull request orphaned. Every rule in knip.json is `warn`, so the exit code stays zero.",
    "name: dead-code-scan",
    "",
    "on:",
    "  pull_request:",
    "    paths:",
    '      - "**/*.ts"',
    '      - "**/*.tsx"',
    '      - "**/*.js"',
    '      - "knip.json"',
    '      - "package.json"',
    "  push:",
    "    branches: [main]",
    "  workflow_dispatch:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  dead-code-scan:",
    "    name: Dead Code Scan (knip)",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    "        with:",
    "          persist-credentials: false",
    "",
    `      - uses: ${ACTION_VERSIONS.setupNode}`,
    "        with:",
    `          node-version: "${nodeVersion}"`,
    "",
    ...(SETUP[packageManager] ?? []),
    `      - run: ${INSTALL[packageManager]}`,
    "",
    "      - name: Run knip",
    "        run: |",
    "          set -euo pipefail",
    "          {",
    "            echo '## knip'",
    "            echo",
    "            echo '```'",
    `            ${RUN[packageManager]} knip || true`,
    "            echo '```'",
    '          } >> "$GITHUB_STEP_SUMMARY"',
    "",
  ].join("\n");
