import { ACTION_VERSIONS } from "./actionVersions.ts";

export const SECRET_SCAN_WORKFLOW_PATH = ".github/workflows/secret-scan.yml";

/**
 * Pinned together — the checksum belongs to this exact archive, so bumping the version without the
 * hash makes the workflow fail loudly at `sha256sum -c` rather than quietly fetching something
 * unverified. Both come from https://github.com/gitleaks/gitleaks/releases.
 */
export const GITLEAKS = {
  version: "8.30.1",
  sha256: "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb",
} as const;

/**
 * Findings get their own exit code, because gitleaks answers "I found a secret" and "I could not
 * run" with the same 1 otherwise — measured, not assumed. Both fail the job either way, so the gate
 * is unaffected; what changes is that the person reading the log is not sent hunting for a leak
 * that does not exist.
 */
export const SECRET_FINDING_EXIT_CODE = 2;

/**
 * The one check here that is a gate from the first run, with no baseline and nothing grandfathered.
 * Every other rule in this tool records what exists and holds the line; a leaked key is already
 * public, and there is no version of "allow the ones we have" that means anything.
 */
export const renderSecretScanWorkflow = (): string =>
  [
    "# Generated by ever-better. A gate from the first run: unlike every other check this tool",
    "# writes, there is no baseline and nothing is grandfathered. A key that has been committed is",
    "# already public, and the fix is rotation rather than a commit.",
    "name: secret-scan",
    "",
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "  workflow_dispatch:",
    "",
    "permissions:",
    "  # The scan only reads the checked-out repository.",
    "  contents: read",
    "",
    "jobs:",
    "  secret-scan:",
    "    name: Secret Scan (gitleaks)",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    "        with:",
    "          # The whole history is the point — a shallow clone misses the commit that leaked.",
    "          fetch-depth: 0",
    "          persist-credentials: false",
    "",
    "      # The gitleaks CLI, not gitleaks-action: the action requires a licence key under a",
    "      # GitHub Organization, while the CLI is MIT. The download is checksum-verified, because",
    "      # fetching a scanner over the network unverified is its own supply-chain hole.",
    "      - name: Install gitleaks",
    "        env:",
    `          GITLEAKS_VERSION: ${GITLEAKS.version}`,
    "          # Refresh alongside any GITLEAKS_VERSION bump, from the release page.",
    `          GITLEAKS_SHA256: ${GITLEAKS.sha256}`,
    "        run: |",
    "          set -euo pipefail",
    '          ARCHIVE="gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"',
    '          curl -sSfL -o "$ARCHIVE" \\',
    '            "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/${ARCHIVE}"',
    '          echo "${GITLEAKS_SHA256}  ${ARCHIVE}" | sha256sum -c -',
    '          sudo tar -xz -C /usr/local/bin -f "$ARCHIVE" gitleaks',
    '          rm -f "$ARCHIVE"',
    "          gitleaks version",
    "",
    "      # `--redact` keeps the secret out of a log anyone can read. `.gitleaksignore` at the repo",
    `      # root is honoured automatically. Exit ${SECRET_FINDING_EXIT_CODE} means findings; 1 also means gitleaks could not`,
    "      # run at all, and telling those apart is what stops a broken scan reading as a leak.",
    "      - name: Run gitleaks over the full history",
    `        run: gitleaks detect --source . --redact --verbose --exit-code ${SECRET_FINDING_EXIT_CODE}`,
    "",
  ].join("\n");
