/**
 * tsconfig is the one thing bootstrap EDITS rather than writes, so the sample shows a before and
 * after rather than a finished file — and says why the expensive flag stayed off.
 */
export const STRICTNESS_SAMPLE = [
  "`bootstrap` does not write a tsconfig; it adds the strictness flags `strict: true` does **not**",
  "include, and only the ones that cost nothing. Type errors have no suppression mechanism —",
  "`--suppress-all` cannot touch them — so a flag that costs 500 errors would leave you with a",
  "failing `typecheck` and no way to stage the work.",
  "",
  "Each flag is priced by enabling it in a temporary config that extends yours and counting the",
  "errors. Measured on a real fixture:",
  "",
  "```",
  "Enabled at zero cost: exactOptionalPropertyTypes, noImplicitReturns,",
  "                      noFallthroughCasesInSwitch, noImplicitOverride,",
  "                      noPropertyAccessFromIndexSignature",
  "Priced and left off — each is a task, not a flag flip:",
  "  noUncheckedIndexedAccess: 1 type errors — left off",
  "```",
  "",
  'Applied to your file by inserting after the `"compilerOptions": {` anchor — never by parsing and',
  "re-serialising, because a tsconfig is usually JSONC and a round trip would delete the comments",
  "explaining why the other options are there:",
  "",
  "```jsonc",
  "{",
  "  // hand-written comment that survives",
  '  "compilerOptions": {',
  "    // Enabled by ever-better after measuring each at zero new type errors.",
  '    "exactOptionalPropertyTypes": true,',
  '    "noImplicitReturns": true,',
  '    "noFallthroughCasesInSwitch": true,',
  '    "noImplicitOverride": true,',
  '    "noPropertyAccessFromIndexSignature": true,',
  '    "target": "ES2022",',
  '    "strict": true',
  "  }",
  "}",
  "```",
].join("\n");
