import type { TierEntry } from "../tier.ts";

export const TIER_CONFIG_FILE = "eslint-tier.config.js";

const IMPORT_LINE = `import everBetterTier from "./${TIER_CONFIG_FILE}";`;

/** Last, so it wins: a later block overrides an earlier one, and this one is the exception list. */
export const SPREAD_BLOCK = ["  // Generated exceptions, last so they win. Regenerate with `ever-better tier`.", "  ...everBetterTier,"];

const quoted = (value: string): string => JSON.stringify(value);

/**
 * Wholly generated and safe to overwrite, the way `eslint-suppressions.json` is. The repository's
 * own config is edited once to import this and never again — rewriting a file somebody else owns on
 * every run is the thing `bootstrap` refuses to do.
 */
export const renderTierConfig = (entries: readonly TierEntry[]): string =>
  [
    "// Generated by ever-better. Do not edit — `ever-better tier` rewrites this file.",
    "//",
    "// Every rule is an error. These file-and-rule pairs were already failing when the tier was",
    "// taken, so they are warnings here instead: visible while you edit, and not a red build.",
    "//",
    "// The list may only shrink. Fix what a file is listed for, re-run `ever-better tier`, and the",
    "// entry goes; a pair that starts failing and is not listed stays an error and fails the build.",
    "",
    "export default [",
    ...entries.flatMap((entry) => [
      "  {",
      `    files: [${quoted(entry.file)}],`,
      "    rules: {",
      ...entry.rules.map((rule) => `      ${quoted(rule)}: "warn",`),
      "    },",
      "  },",
    ]),
    "];",
    "",
  ].join("\n");

/** Present when the repository's config already spreads the generated list. */
export const importsTier = (source: string): boolean => source.includes(IMPORT_LINE) && source.includes("...everBetterTier");

export const withTierImport = (source: string): string => `${IMPORT_LINE}\n${source}`;
