import type { TierEntry } from "../tier.ts";

/**
 * Set while `ever-better tier` recomputes the list. The exceptions must not apply to the scan that
 * regenerates them, or every listed pair would read as fixed and the list would empty out.
 *
 * Forcing the rules back to `error` on the command line was the obvious way to do this and it does
 * not work: `--rule` is global, so a type-aware rule gets applied to files outside the type program
 * — a generated `eslint.config.js`, any plain JS — and ESLint aborts with "you have used a rule
 * which requires type information". Measured against ESLint 10, not assumed.
 */
export const TIER_RECOMPUTE_ENV = "EVER_BETTER_TIER_RECOMPUTE";

export type ModuleSystem = "esm" | "cjs";

const IDENTIFIER = "everBetterTier";

/** First line of every file this renders, and the proof that a file found on disk is ours to delete. */
export const GENERATED_MARKER = "// Generated by ever-better. Do not edit — `ever-better tier` rewrites this file.";

/**
 * What the config being wired actually is, which the extension alone does not answer. A flat config
 * may be CommonJS in a plain `eslint.config.js`, and prepending an `import` to it leaves ESLint with
 * `ReferenceError: module is not defined in ES module scope` — no linter, and `tier` exits 0.
 *
 * `"type": "module"` decides a `.js` file first, because Node decides it first — a CommonJS-looking
 * `.js` config in an ESM package is simply broken, and nothing prepended to it helps. Below that,
 * `module.exports` is the reliable marker: a flat config has to export its array, and that is the
 * only way a CommonJS one can.
 */
export const moduleSystemOf = (eslintConfigName: string, source: string, packageType: string | null): ModuleSystem => {
  if (eslintConfigName.endsWith(".cjs")) return "cjs";
  if (eslintConfigName.endsWith(".mjs") || eslintConfigName.endsWith(".ts")) return "esm";
  if (packageType === "module") return "esm";
  return source.includes("module.exports") ? "cjs" : "esm";
};

/**
 * Never a bare `.js`. That extension means "whatever the nearest package.json says", so in a package
 * without `"type": "module"` — the common case, and the one `bootstrap` writes `eslint.config.mjs`
 * for — an ESM file becomes CommonJS. Node below 20.19 refuses it outright, and above it warns
 * `MODULE_TYPELESS_PACKAGE_JSON` and reparses on every lint. `.mjs` and `.cjs` say what they are.
 */
export const tierConfigFileName = (system: ModuleSystem): string => (system === "cjs" ? "eslint-tier.config.cjs" : "eslint-tier.config.mjs");

/** Every name this has ever generated, so a rename can find and remove the one it replaces. */
export const TIER_CONFIG_NAMES = ["eslint-tier.config.mjs", "eslint-tier.config.cjs", "eslint-tier.config.js"];

/** Last, so it wins: a later block overrides an earlier one, and this one is the exception list. */
export const SPREAD_BLOCK = ["  // Generated exceptions, last so they win. Regenerate with `ever-better tier`.", `  ...${IDENTIFIER},`];

const quoted = (value: string): string => JSON.stringify(value);

/**
 * A flat-config `files` entry is a GLOB, not a literal path, and real repositories contain paths
 * that are also glob syntax — `pages/[id].tsx` is Next.js's routing convention, and this tool
 * generates a Next config. Unescaped, `pages/[id].js` is a character class: it matches
 * `pages/i.js`, does NOT match the file ESLint recorded, and so leaves the excused file failing
 * while quietly downgrading a different one.
 */
const GLOB_META = /[\\*?[\]{}()!+@|]/g;

const asLiteralGlob = (file: string): string => file.replace(GLOB_META, "\\$&");

const HEADER = [
  GENERATED_MARKER,
  "//",
  "// Every rule is an error. These file-and-rule pairs were already failing when the tier was",
  "// taken, so they are warnings here instead: visible while you edit, and not a red build.",
  "//",
  "// The list may only shrink. Fix what a file is listed for, re-run `ever-better tier`, and the",
  "// entry goes; a pair that starts failing and is not listed stays an error and fails the build.",
  "",
];

const GUARD = [
  "// `ever-better tier` sets this while it recomputes the list. The exceptions must not apply to",
  "// the scan that regenerates them, or every entry below would read as already fixed.",
  `const recomputing = process.env.${TIER_RECOMPUTE_ENV} === "1";`,
  "",
];

/**
 * This file exempts itself from linting, in both branches. It is generated, so nobody can act on a
 * finding in it — and one arrives on its own: a long enough path pushes a `files:` line past the
 * repository's `printWidth` and `prettier/prettier` reports an error in a file the header tells the
 * reader not to edit. Worse, that error appears AFTER the scan that produced the list, so nothing
 * excuses it: the build goes red and stays red. An object carrying only `ignores` is global ignores
 * wherever it appears, including spread in last — verified against ESLint 10, not assumed.
 */
const ignoreSelf = (tierConfigName: string): string[] => [`const ignoreSelf = { ignores: [${quoted(tierConfigName)}] };`, ""];

export const renderTierConfig = (entries: readonly TierEntry[], tierConfigName: string): string => {
  const cjs = tierConfigName.endsWith(".cjs");
  return [
    ...HEADER,
    cjs ? 'const process = require("node:process");' : 'import process from "node:process";',
    "",
    ...GUARD,
    ...ignoreSelf(tierConfigName),
    "const exceptions = [",
    ...entries.flatMap((entry) => [
      "  {",
      `    files: [${quoted(asLiteralGlob(entry.file))}],`,
      "    rules: {",
      ...entry.rules.map((rule) => `      ${quoted(rule)}: "warn",`),
      "    },",
      "  },",
    ]),
    "];",
    "",
    `${cjs ? "module.exports =" : "export default"} recomputing ? [ignoreSelf] : [ignoreSelf, ...exceptions];`,
    "",
  ].join("\n");
};

const importLine = (tierConfigName: string): string =>
  tierConfigName.endsWith(".cjs") ? `const ${IDENTIFIER} = require("./${tierConfigName}");` : `import ${IDENTIFIER} from "./${tierConfigName}";`;

const isImportLine = (line: string): boolean => line.startsWith(`import ${IDENTIFIER} from`) || line.startsWith(`const ${IDENTIFIER} = require(`);

/** Whether any generated list is wired in, whichever file it names. */
export const hasTierImport = (source: string): boolean => source.split("\n").some(isImportLine);

/**
 * Wired to THIS file, not merely wired. A config left pointing at a name an earlier run generated
 * keeps applying that file's exceptions while the ledger and the new file say something else — the
 * two drift apart silently, and the older one is the more permissive.
 */
export const importsTier = (source: string, tierConfigName: string): boolean => source.split("\n").includes(importLine(tierConfigName));

/** Repoints an existing import rather than adding a second one: two bindings is a syntax error. */
export const withTierImport = (source: string, tierConfigName: string): string => {
  const lines = source.split("\n");
  const at = lines.findIndex(isImportLine);
  if (at === -1) return `${importLine(tierConfigName)}\n${source}`;
  return [...lines.slice(0, at), importLine(tierConfigName), ...lines.slice(at + 1)].join("\n");
};
