import { ACTION_VERSIONS } from "./actionVersions.ts";
import type { PackageManager, ScriptCoverage } from "../types.ts";

export type WorkflowOptions = {
  packageManager: PackageManager;
  scripts: ScriptCoverage;
  nodeVersion: string;
};

const INSTALL: Record<PackageManager, string> = {
  yarn: "yarn install --frozen-lockfile",
  npm: "npm ci",
  pnpm: "pnpm install --frozen-lockfile",
  bun: "bun install --frozen-lockfile",
};

const RUN: Record<PackageManager, string> = {
  yarn: "yarn",
  npm: "npm run",
  pnpm: "pnpm",
  bun: "bun run",
};

const SETUP: Partial<Record<PackageManager, string[]>> = {
  pnpm: [`      - uses: ${ACTION_VERSIONS.pnpmSetup}`, ""],
  bun: [`      - uses: ${ACTION_VERSIONS.bunSetup}`, ""],
};

const STEP_ORDER: readonly (keyof ScriptCoverage)[] = ["lint", "typecheck", "build", "test"];

const scriptSteps = (options: WorkflowOptions): string[] =>
  STEP_ORDER.filter((name) => options.scripts[name]).flatMap((name) => [
    `      - name: ${name}`,
    `        run: ${RUN[options.packageManager]} ${name}`,
  ]);

/**
 * Three runners, not one. Path separators, case-insensitive filesystems and file watching are the
 * three places a green Linux build says nothing at all about the other two platforms.
 */
export const renderWorkflow = (options: WorkflowOptions): string =>
  [
    "# Generated by ever-better. Edit freely.",
    "name: ci",
    "",
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  ci:",
    "    runs-on: ${{ matrix.os }}",
    "    timeout-minutes: 20",
    "    strategy:",
    "      fail-fast: false",
    "      matrix:",
    "        os: [ubuntu-latest, macos-latest, windows-latest]",
    "    steps:",
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    "        with:",
    "          persist-credentials: false",
    "",
    ...(SETUP[options.packageManager] ?? []),
    `      - uses: ${ACTION_VERSIONS.setupNode}`,
    "        with:",
    `          node-version: "${options.nodeVersion}"`,
    "",
    `      - run: ${INSTALL[options.packageManager]}`,
    "",
    ...scriptSteps(options),
    "",
    "      - name: ever-better check",
    "        run: npx ever-better check",
    "",
  ].join("\n");
