import type { SourceFile } from "./types.ts";

export type CatalogEntry = {
  name: string;
  file: string;
  line: number;
  /** First sentence of the doc comment above it, when there is one. */
  summary: string | null;
};

/**
 * `export const name = (` and `export function name(` — the two shapes that matter in practice.
 * The optional `<...>` is not decoration: a generic arrow is ordinary TypeScript, and without it
 * every generic helper is missing from a catalogue whose whole job is to be complete.
 */
const ARROW = /^export const ([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*(?:async\s*)?(?:<[^>]*>\s*)?\(/;
const FUNCTION = /^export (?:async )?function ([A-Za-z_$][\w$]*)\s*[(<]/;

const DOC_LINE = /^\s*\*\s?(.*)$/;

/**
 * The summary is the doc comment's first sentence, not its first line: these are written to wrap,
 * so a first line alone usually stops mid-clause.
 */
const summaryAbove = (lines: readonly string[], index: number): string | null => {
  if (lines[index - 1]?.trim() !== "*/") return null;
  const collected: string[] = [];
  for (let cursor = index - 2; cursor >= 0; cursor -= 1) {
    const line = lines[cursor] ?? "";
    if (line.includes("/**")) break;
    const match = DOC_LINE.exec(line);
    if (!match) break;
    collected.unshift(match[1] ?? "");
  }
  const text = collected.join(" ").trim();
  if (text.length === 0) return null;
  const sentence = /^(.*?[.!?])(\s|$)/.exec(text);
  return (sentence?.[1] ?? text).trim();
};

/** Pure: given a file's text, the exported callables in it. */
export const extractExports = (source: string, file: string): CatalogEntry[] => {
  const lines = source.split("\n");
  return lines.flatMap((line, index) => {
    const name = (ARROW.exec(line) ?? FUNCTION.exec(line))?.[1];
    if (name === undefined) return [];
    return [{ name, file, line: index + 1, summary: summaryAbove(lines, index) }];
  });
};

const byName = (left: CatalogEntry, right: CatalogEntry): number => left.name.localeCompare(right.name);

const directoryOf = (file: string): string => {
  const slash = file.lastIndexOf("/");
  return slash < 0 ? "." : file.slice(0, slash);
};

const HEADER = [
  "# Shared helpers",
  "",
  "<!-- Generated by `ever-better catalog`. Regenerate rather than editing. -->",
  "",
  "Read this before writing a helper. The failure it exists to prevent is the same function written",
  "a sixth time under a sixth name, which no linter reports and which duplication detection only",
  "notices once the copies are textually similar — and independently written ones rarely are.",
  "",
];

export const renderCatalog = (entries: readonly CatalogEntry[]): string => {
  if (entries.length === 0) {
    return [...HEADER, "No exported functions found.", ""].join("\n");
  }
  const directories = [...new Set(entries.map((entry) => directoryOf(entry.file)))].sort((a, b) => a.localeCompare(b));
  const sections = directories.flatMap((directory) => [
    `## ${directory}`,
    "",
    "| Helper | Where | What it does |",
    "| --- | --- | --- |",
    ...entries
      .filter((entry) => directoryOf(entry.file) === directory)
      .sort(byName)
      .map((entry) => `| \`${entry.name}\` | ${entry.file}:${entry.line} | ${entry.summary ?? ""} |`),
    "",
  ]);
  return [...HEADER, `${entries.length} exported functions.`, "", ...sections].join("\n");
};

export const catalogSources = (files: readonly SourceFile[]): SourceFile[] =>
  files.filter((file) => !file.path.includes("test") && !file.path.endsWith(".d.ts") && ["ts", "tsx", "mts", "js", "mjs"].includes(file.ext));
